apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-heart-disease-api
  labels:
    app: {{ .Release.Name }}-heart-disease-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-heart-disease-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-heart-disease-api
    spec:
      containers:
        - name: heart-disease-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.readinessInitialDelay }}
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.livenessInitialDelay }}
            periodSeconds: 20
